// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: api/common/c_counter.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// 通用计数器类型
public enum CommonCounterIDType: SwiftProtobuf.Enum {
  public typealias RawValue = Int

  /// @String(未知id)
  case citUnknown // = 0

  /// @String(会话消息id)
  case citChatMessage // = 1

  /// @String(分配用户id)
  case citAssignUser // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .citUnknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .citUnknown
    case 1: self = .citChatMessage
    case 2: self = .citAssignUser
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .citUnknown: return 0
    case .citChatMessage: return 1
    case .citAssignUser: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension CommonCounterIDType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [CommonCounterIDType] = [
    .citUnknown,
    .citChatMessage,
    .citAssignUser,
  ]
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension CommonCounterIDType: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension CommonCounterIDType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "CIT_UNKNOWN"),
    1: .same(proto: "CIT_CHAT_MESSAGE"),
    2: .same(proto: "CIT_ASSIGN_USER"),
  ]
}
