// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: api/core/cache.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// get request
public struct Api_Core_GetReqV1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: UInt64 = 0

  /// 执行次数
  public var execNum: UInt64 = 0

  /// 协程数量
  public var cNum: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// get response
public struct Api_Core_GetRespV1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: UInt64 = 0

  /// 执行次数
  public var execNum: UInt64 = 0

  public var value: UInt64 = 0

  public var valueTime: UInt64 = 0

  /// 执行时间
  public var execMilTime: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_SetReqV1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: UInt64 = 0

  public var value: UInt64 = 0

  /// 执行次数
  public var execNum: UInt64 = 0

  /// 协程数量
  public var cNum: UInt64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_SetRespV1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var key: UInt64 = 0

  /// 执行次数
  public var execNum: UInt64 = 0

  public var value: UInt64 = 0

  public var valueTime: UInt64 = 0

  /// 执行时间
  public var execMilTime: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Api_Core_GetReqV1: @unchecked Sendable {}
extension Api_Core_GetRespV1: @unchecked Sendable {}
extension Api_Core_SetReqV1: @unchecked Sendable {}
extension Api_Core_SetRespV1: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "api.core"

extension Api_Core_GetReqV1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetReqV1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "key"),
    2: .standard(proto: "exec_num"),
    3: .standard(proto: "c_num"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.key) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.execNum) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.cNum) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.key != 0 {
      try visitor.visitSingularUInt64Field(value: self.key, fieldNumber: 1)
    }
    if self.execNum != 0 {
      try visitor.visitSingularUInt64Field(value: self.execNum, fieldNumber: 2)
    }
    if self.cNum != 0 {
      try visitor.visitSingularUInt64Field(value: self.cNum, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_GetReqV1, rhs: Api_Core_GetReqV1) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.execNum != rhs.execNum {return false}
    if lhs.cNum != rhs.cNum {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_GetRespV1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetRespV1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "key"),
    2: .standard(proto: "exec_num"),
    3: .same(proto: "value"),
    4: .standard(proto: "value_time"),
    5: .standard(proto: "exec_mil_time"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.key) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.execNum) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.value) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.valueTime) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.execMilTime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.key != 0 {
      try visitor.visitSingularUInt64Field(value: self.key, fieldNumber: 1)
    }
    if self.execNum != 0 {
      try visitor.visitSingularUInt64Field(value: self.execNum, fieldNumber: 2)
    }
    if self.value != 0 {
      try visitor.visitSingularUInt64Field(value: self.value, fieldNumber: 3)
    }
    if self.valueTime != 0 {
      try visitor.visitSingularUInt64Field(value: self.valueTime, fieldNumber: 4)
    }
    if self.execMilTime != 0 {
      try visitor.visitSingularInt64Field(value: self.execMilTime, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_GetRespV1, rhs: Api_Core_GetRespV1) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.execNum != rhs.execNum {return false}
    if lhs.value != rhs.value {return false}
    if lhs.valueTime != rhs.valueTime {return false}
    if lhs.execMilTime != rhs.execMilTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_SetReqV1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetReqV1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "key"),
    2: .same(proto: "value"),
    3: .standard(proto: "exec_num"),
    4: .standard(proto: "c_num"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.key) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.value) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.execNum) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.cNum) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.key != 0 {
      try visitor.visitSingularUInt64Field(value: self.key, fieldNumber: 1)
    }
    if self.value != 0 {
      try visitor.visitSingularUInt64Field(value: self.value, fieldNumber: 2)
    }
    if self.execNum != 0 {
      try visitor.visitSingularUInt64Field(value: self.execNum, fieldNumber: 3)
    }
    if self.cNum != 0 {
      try visitor.visitSingularUInt64Field(value: self.cNum, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_SetReqV1, rhs: Api_Core_SetReqV1) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.value != rhs.value {return false}
    if lhs.execNum != rhs.execNum {return false}
    if lhs.cNum != rhs.cNum {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_SetRespV1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetRespV1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "key"),
    2: .standard(proto: "exec_num"),
    3: .same(proto: "value"),
    4: .standard(proto: "value_time"),
    5: .standard(proto: "exec_mil_time"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.key) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.execNum) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.value) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.valueTime) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.execMilTime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.key != 0 {
      try visitor.visitSingularUInt64Field(value: self.key, fieldNumber: 1)
    }
    if self.execNum != 0 {
      try visitor.visitSingularUInt64Field(value: self.execNum, fieldNumber: 2)
    }
    if self.value != 0 {
      try visitor.visitSingularUInt64Field(value: self.value, fieldNumber: 3)
    }
    if self.valueTime != 0 {
      try visitor.visitSingularUInt64Field(value: self.valueTime, fieldNumber: 4)
    }
    if self.execMilTime != 0 {
      try visitor.visitSingularInt64Field(value: self.execMilTime, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_SetRespV1, rhs: Api_Core_SetRespV1) -> Bool {
    if lhs.key != rhs.key {return false}
    if lhs.execNum != rhs.execNum {return false}
    if lhs.value != rhs.value {return false}
    if lhs.valueTime != rhs.valueTime {return false}
    if lhs.execMilTime != rhs.execMilTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
