// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: api/core/chat.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

///分页结构体
public struct Api_Core_Pagination {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///当前页码
  public var page: Int32 = 0

  ///分页大小
  public var pagesize: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 聊天会话列表
public struct Api_Core_ChatListQueryRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var workerID: Int32 = 0

  public var flag: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 聊天会话列表
public struct Api_Core_ChatListQueryPageRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var page: Api_Core_Pagination {
    get {return _page ?? Api_Core_Pagination()}
    set {_page = newValue}
  }
  /// Returns true if `page` has been explicitly set.
  public var hasPage: Bool {return self._page != nil}
  /// Clears the value of `page`. Subsequent reads from it will return its default value.
  public mutating func clearPage() {self._page = nil}

  public var workerID: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _page: Api_Core_Pagination? = nil
}

/// 历史聊天会话列表
public struct Api_Core_HistoryClientSessionsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var workerID: Int32 = 0

  ///开始查询时间
  public var startTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _startTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_startTime = newValue}
  }
  /// Returns true if `startTime` has been explicitly set.
  public var hasStartTime: Bool {return self._startTime != nil}
  /// Clears the value of `startTime`. Subsequent reads from it will return its default value.
  public mutating func clearStartTime() {self._startTime = nil}

  ///结束
  public var endTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _endTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_endTime = newValue}
  }
  /// Returns true if `endTime` has been explicitly set.
  public var hasEndTime: Bool {return self._endTime != nil}
  /// Clears the value of `endTime`. Subsequent reads from it will return its default value.
  public mutating func clearEndTime() {self._endTime = nil}

  /// 咨询id
  public var consultID: UInt32 = 0

  /// 用户id
  public var ownerID: Int32 = 0

  /// 用户昵称
  public var nickname: String = String()

  /// 分页大小
  public var pageSize: Int32 = 0

  /// 分页/最后时间
  public var lastCreatedAt: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _startTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _endTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct Api_Core_HistoryClientSessionsResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chatSessions: [CommonChatItem] = []

  /// 分页/最后时间
  public var lastCreatedAt: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 首页聊天会话列表
public struct Api_Core_IndexClientSessionsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///开始查询时间
  public var startTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _startTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_startTime = newValue}
  }
  /// Returns true if `startTime` has been explicitly set.
  public var hasStartTime: Bool {return self._startTime != nil}
  /// Clears the value of `startTime`. Subsequent reads from it will return its default value.
  public mutating func clearStartTime() {self._startTime = nil}

  ///结束
  public var endTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _endTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_endTime = newValue}
  }
  /// Returns true if `endTime` has been explicitly set.
  public var hasEndTime: Bool {return self._endTime != nil}
  /// Clears the value of `endTime`. Subsequent reads from it will return its default value.
  public mutating func clearEndTime() {self._endTime = nil}

  /// 页数
  public var page: UInt32 = 0

  /// 每页大小
  public var pageSize: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _startTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _endTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct Api_Core_IndexClientSessionsResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chatSessions: [CommonChatItem] = []

  public var total: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_ChatListQueryResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chats: [CommonChatItem] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_ChatListQueryPageResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  ///总量
  public var total: Int32 = 0

  public var chats: [CommonChatItem] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// 标记已读
public struct Api_Core_ChatMarkReadRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chatID: Int64 = 0

  /// 咨询类型
  public var consultID: Int64 = 0

  /// 消息ID
  public var msgID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_OrphanResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var workerID: Int32 = 0

  public var nick: String = String()

  public var avatar: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_MarkRepliedRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chatID: Int64 = 0

  /// 咨询类型
  public var consultID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_ChatListQueryUserRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var userID: Int32 = 0

  public var registerType: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_OrphanReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chatID: Int64 = 0

  /// 咨询类型
  public var consultID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_GetChatSessionStateRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 商户ID
  public var tenantID: Int32 = 0

  /// 咨询类型
  public var consultID: Int64 = 0

  /// 用户id
  public var ownerID: Int32 = 0

  public var ownerRole: Int32 = 0

  /// 会话ID
  public var chatID: Int64 = 0

  /// 消息id，配合会话id和咨询id可以查询指定消息
  public var msgID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_GetChatSessionStateResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 商户ID
  public var tenantID: Int32 {
    get {return _storage._tenantID}
    set {_uniqueStorage()._tenantID = newValue}
  }

  /// 咨询类型
  public var consultID: Int64 {
    get {return _storage._consultID}
    set {_uniqueStorage()._consultID = newValue}
  }

  /// 用户id
  public var ownerID: Int32 {
    get {return _storage._ownerID}
    set {_uniqueStorage()._ownerID = newValue}
  }

  /// 用户角色
  public var ownerRole: Int32 {
    get {return _storage._ownerRole}
    set {_uniqueStorage()._ownerRole = newValue}
  }

  /// 多少秒前分配任务
  public var assignTime: Int64 {
    get {return _storage._assignTime}
    set {_uniqueStorage()._assignTime = newValue}
  }

  /// 会话多少秒前开始
  public var sessionStartTime: Int64 {
    get {return _storage._sessionStartTime}
    set {_uniqueStorage()._sessionStartTime = newValue}
  }

  /// 客户多少秒前发言
  public var clientMessageTime: Int64 {
    get {return _storage._clientMessageTime}
    set {_uniqueStorage()._clientMessageTime = newValue}
  }

  /// 客户多少秒前第一次发言
  public var clientFirstTime: Int64 {
    get {return _storage._clientFirstTime}
    set {_uniqueStorage()._clientFirstTime = newValue}
  }

  /// 客服id
  public var workerID: Int32 {
    get {return _storage._workerID}
    set {_uniqueStorage()._workerID = newValue}
  }

  /// 客服多少秒前是否在线
  public var workerPingTime: Int64 {
    get {return _storage._workerPingTime}
    set {_uniqueStorage()._workerPingTime = newValue}
  }

  /// 客服多少秒前第一次发言
  public var workerFirstTime: Int64 {
    get {return _storage._workerFirstTime}
    set {_uniqueStorage()._workerFirstTime = newValue}
  }

  /// 客服多少秒前发言
  public var workerMessageTime: Int64 {
    get {return _storage._workerMessageTime}
    set {_uniqueStorage()._workerMessageTime = newValue}
  }

  /// 咨询类型
  public var workerConsultID: Int64 {
    get {return _storage._workerConsultID}
    set {_uniqueStorage()._workerConsultID = newValue}
  }

  /// 多少秒前转入任务
  public var inTime: Int64 {
    get {return _storage._inTime}
    set {_uniqueStorage()._inTime = newValue}
  }

  /// 多少秒前转出任务
  public var outTime: Int64 {
    get {return _storage._outTime}
    set {_uniqueStorage()._outTime = newValue}
  }

  /// 多少秒前最后活动
  public var lastTime: Int64 {
    get {return _storage._lastTime}
    set {_uniqueStorage()._lastTime = newValue}
  }

  /// 是否已超时
  public var timeout: Int32 {
    get {return _storage._timeout}
    set {_uniqueStorage()._timeout = newValue}
  }

  /// 是否已超时
  public var waitResponse: Int32 {
    get {return _storage._waitResponse}
    set {_uniqueStorage()._waitResponse = newValue}
  }

  /// 是否已超时
  public var isProcess: Int32 {
    get {return _storage._isProcess}
    set {_uniqueStorage()._isProcess = newValue}
  }

  /// 是否已超时
  public var isReceive: Int32 {
    get {return _storage._isReceive}
    set {_uniqueStorage()._isReceive = newValue}
  }

  /// 是转入
  public var isIn: Int32 {
    get {return _storage._isIn}
    set {_uniqueStorage()._isIn = newValue}
  }

  /// 是否转出
  public var isOut: Int32 {
    get {return _storage._isOut}
    set {_uniqueStorage()._isOut = newValue}
  }

  /// 是否可见
  public var visible: Int32 {
    get {return _storage._visible}
    set {_uniqueStorage()._visible = newValue}
  }

  /// 客户状态
  public var state: CommonChatState {
    get {return _storage._state}
    set {_uniqueStorage()._state = newValue}
  }

  /// 客服状态
  public var workerState: Api_Common_WorkerState {
    get {return _storage._workerState}
    set {_uniqueStorage()._workerState = newValue}
  }

  /// 最后消息
  public var lastMessage: CommonMessage {
    get {return _storage._lastMessage ?? CommonMessage()}
    set {_uniqueStorage()._lastMessage = newValue}
  }
  /// Returns true if `lastMessage` has been explicitly set.
  public var hasLastMessage: Bool {return _storage._lastMessage != nil}
  /// Clears the value of `lastMessage`. Subsequent reads from it will return its default value.
  public mutating func clearLastMessage() {_uniqueStorage()._lastMessage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Api_Core_GetChatStateReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 咨询类型
  public var consultID: Int64 = 0

  /// 会话ID
  public var chatIds: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_StateItem {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var chatID: Int64 = 0

  public var userID: Int32 = 0

  /// 会话是否过期
  public var isTimeOut: Bool = false

  /// 会话剩余过期时间 秒
  public var expireSeconds: Int64 = 0

  /// 当前时间戳
  public var nowTime: Int64 = 0

  /// 当前绑定 客服
  public var workerID: Int32 = 0

  /// 最后消息时间
  public var lastMsgTime: Int64 = 0

  /// 分流时间
  public var assignTime: Int64 = 0

  /// 转入时间
  public var transferInTime: Int64 = 0

  /// 转出时间
  public var transferOutTime: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_GetChatStateResp {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var consultID: Int64 = 0

  public var items: [Api_Core_StateItem] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Api_Core_GetChatStateRespV1 {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var consultID: Int64 = 0

  public var chatIds: [Int64] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// get chat faq remark req
public struct Api_Core_ChatFaqRemarkReq {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// FAQ
  public var chatID: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// get chat faq remark resp
public struct Api_Core_ChatFaqRemarkResp {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// FAQ
  public var chatRemark: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Api_Core_Pagination: @unchecked Sendable {}
extension Api_Core_ChatListQueryRequest: @unchecked Sendable {}
extension Api_Core_ChatListQueryPageRequest: @unchecked Sendable {}
extension Api_Core_HistoryClientSessionsRequest: @unchecked Sendable {}
extension Api_Core_HistoryClientSessionsResponse: @unchecked Sendable {}
extension Api_Core_IndexClientSessionsRequest: @unchecked Sendable {}
extension Api_Core_IndexClientSessionsResponse: @unchecked Sendable {}
extension Api_Core_ChatListQueryResponse: @unchecked Sendable {}
extension Api_Core_ChatListQueryPageResponse: @unchecked Sendable {}
extension Api_Core_ChatMarkReadRequest: @unchecked Sendable {}
extension Api_Core_OrphanResponse: @unchecked Sendable {}
extension Api_Core_MarkRepliedRequest: @unchecked Sendable {}
extension Api_Core_ChatListQueryUserRequest: @unchecked Sendable {}
extension Api_Core_OrphanReq: @unchecked Sendable {}
extension Api_Core_GetChatSessionStateRequest: @unchecked Sendable {}
extension Api_Core_GetChatSessionStateResponse: @unchecked Sendable {}
extension Api_Core_GetChatStateReq: @unchecked Sendable {}
extension Api_Core_StateItem: @unchecked Sendable {}
extension Api_Core_GetChatStateResp: @unchecked Sendable {}
extension Api_Core_GetChatStateRespV1: @unchecked Sendable {}
extension Api_Core_ChatFaqRemarkReq: @unchecked Sendable {}
extension Api_Core_ChatFaqRemarkResp: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "api.core"

extension Api_Core_Pagination: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Pagination"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "page"),
    2: .same(proto: "pagesize"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.page) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.pagesize) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.page != 0 {
      try visitor.visitSingularInt32Field(value: self.page, fieldNumber: 1)
    }
    if self.pagesize != 0 {
      try visitor.visitSingularInt32Field(value: self.pagesize, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_Pagination, rhs: Api_Core_Pagination) -> Bool {
    if lhs.page != rhs.page {return false}
    if lhs.pagesize != rhs.pagesize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_ChatListQueryRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatListQueryRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "worker_id"),
    2: .same(proto: "flag"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.workerID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.flag) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.workerID != 0 {
      try visitor.visitSingularInt32Field(value: self.workerID, fieldNumber: 1)
    }
    if self.flag != false {
      try visitor.visitSingularBoolField(value: self.flag, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_ChatListQueryRequest, rhs: Api_Core_ChatListQueryRequest) -> Bool {
    if lhs.workerID != rhs.workerID {return false}
    if lhs.flag != rhs.flag {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_ChatListQueryPageRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatListQueryPageRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "page"),
    2: .standard(proto: "worker_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._page) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.workerID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._page {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.workerID != 0 {
      try visitor.visitSingularInt32Field(value: self.workerID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_ChatListQueryPageRequest, rhs: Api_Core_ChatListQueryPageRequest) -> Bool {
    if lhs._page != rhs._page {return false}
    if lhs.workerID != rhs.workerID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_HistoryClientSessionsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HistoryClientSessionsRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "worker_id"),
    2: .standard(proto: "start_time"),
    3: .standard(proto: "end_time"),
    5: .standard(proto: "consult_id"),
    6: .standard(proto: "owner_id"),
    7: .same(proto: "nickname"),
    8: .standard(proto: "page_size"),
    9: .standard(proto: "last_created_at"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.workerID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._startTime) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._endTime) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.consultID) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.ownerID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.nickname) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.pageSize) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.lastCreatedAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.workerID != 0 {
      try visitor.visitSingularInt32Field(value: self.workerID, fieldNumber: 1)
    }
    try { if let v = self._startTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._endTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    if self.consultID != 0 {
      try visitor.visitSingularUInt32Field(value: self.consultID, fieldNumber: 5)
    }
    if self.ownerID != 0 {
      try visitor.visitSingularInt32Field(value: self.ownerID, fieldNumber: 6)
    }
    if !self.nickname.isEmpty {
      try visitor.visitSingularStringField(value: self.nickname, fieldNumber: 7)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularInt32Field(value: self.pageSize, fieldNumber: 8)
    }
    if self.lastCreatedAt != 0 {
      try visitor.visitSingularInt64Field(value: self.lastCreatedAt, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_HistoryClientSessionsRequest, rhs: Api_Core_HistoryClientSessionsRequest) -> Bool {
    if lhs.workerID != rhs.workerID {return false}
    if lhs._startTime != rhs._startTime {return false}
    if lhs._endTime != rhs._endTime {return false}
    if lhs.consultID != rhs.consultID {return false}
    if lhs.ownerID != rhs.ownerID {return false}
    if lhs.nickname != rhs.nickname {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.lastCreatedAt != rhs.lastCreatedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_HistoryClientSessionsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HistoryClientSessionsResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_sessions"),
    2: .standard(proto: "last_created_at"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.chatSessions) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.lastCreatedAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chatSessions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.chatSessions, fieldNumber: 1)
    }
    if self.lastCreatedAt != 0 {
      try visitor.visitSingularInt64Field(value: self.lastCreatedAt, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_HistoryClientSessionsResponse, rhs: Api_Core_HistoryClientSessionsResponse) -> Bool {
    if lhs.chatSessions != rhs.chatSessions {return false}
    if lhs.lastCreatedAt != rhs.lastCreatedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_IndexClientSessionsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IndexClientSessionsRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "start_time"),
    2: .standard(proto: "end_time"),
    3: .same(proto: "page"),
    4: .same(proto: "pageSize"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._startTime) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._endTime) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.page) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.pageSize) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._startTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._endTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.page != 0 {
      try visitor.visitSingularUInt32Field(value: self.page, fieldNumber: 3)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularUInt32Field(value: self.pageSize, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_IndexClientSessionsRequest, rhs: Api_Core_IndexClientSessionsRequest) -> Bool {
    if lhs._startTime != rhs._startTime {return false}
    if lhs._endTime != rhs._endTime {return false}
    if lhs.page != rhs.page {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_IndexClientSessionsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IndexClientSessionsResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_sessions"),
    2: .same(proto: "total"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.chatSessions) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.total) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chatSessions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.chatSessions, fieldNumber: 1)
    }
    if self.total != 0 {
      try visitor.visitSingularInt64Field(value: self.total, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_IndexClientSessionsResponse, rhs: Api_Core_IndexClientSessionsResponse) -> Bool {
    if lhs.chatSessions != rhs.chatSessions {return false}
    if lhs.total != rhs.total {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_ChatListQueryResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatListQueryResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "chats"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.chats) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chats.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.chats, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_ChatListQueryResponse, rhs: Api_Core_ChatListQueryResponse) -> Bool {
    if lhs.chats != rhs.chats {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_ChatListQueryPageResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatListQueryPageResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "total"),
    2: .same(proto: "chats"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.total) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.chats) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.total != 0 {
      try visitor.visitSingularInt32Field(value: self.total, fieldNumber: 1)
    }
    if !self.chats.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.chats, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_ChatListQueryPageResponse, rhs: Api_Core_ChatListQueryPageResponse) -> Bool {
    if lhs.total != rhs.total {return false}
    if lhs.chats != rhs.chats {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_ChatMarkReadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatMarkReadRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_id"),
    2: .standard(proto: "consult_id"),
    3: .standard(proto: "msg_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.chatID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.consultID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.msgID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chatID != 0 {
      try visitor.visitSingularInt64Field(value: self.chatID, fieldNumber: 1)
    }
    if self.consultID != 0 {
      try visitor.visitSingularInt64Field(value: self.consultID, fieldNumber: 2)
    }
    if !self.msgID.isEmpty {
      try visitor.visitSingularStringField(value: self.msgID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_ChatMarkReadRequest, rhs: Api_Core_ChatMarkReadRequest) -> Bool {
    if lhs.chatID != rhs.chatID {return false}
    if lhs.consultID != rhs.consultID {return false}
    if lhs.msgID != rhs.msgID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_OrphanResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OrphanResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "worker_id"),
    2: .same(proto: "nick"),
    3: .same(proto: "avatar"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.workerID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.nick) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.avatar) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.workerID != 0 {
      try visitor.visitSingularInt32Field(value: self.workerID, fieldNumber: 1)
    }
    if !self.nick.isEmpty {
      try visitor.visitSingularStringField(value: self.nick, fieldNumber: 2)
    }
    if !self.avatar.isEmpty {
      try visitor.visitSingularStringField(value: self.avatar, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_OrphanResponse, rhs: Api_Core_OrphanResponse) -> Bool {
    if lhs.workerID != rhs.workerID {return false}
    if lhs.nick != rhs.nick {return false}
    if lhs.avatar != rhs.avatar {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_MarkRepliedRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MarkRepliedRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_id"),
    2: .standard(proto: "consult_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.chatID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.consultID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chatID != 0 {
      try visitor.visitSingularInt64Field(value: self.chatID, fieldNumber: 1)
    }
    if self.consultID != 0 {
      try visitor.visitSingularInt64Field(value: self.consultID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_MarkRepliedRequest, rhs: Api_Core_MarkRepliedRequest) -> Bool {
    if lhs.chatID != rhs.chatID {return false}
    if lhs.consultID != rhs.consultID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_ChatListQueryUserRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatListQueryUserRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "user_id"),
    2: .standard(proto: "register_type"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.userID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.registerType) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.userID != 0 {
      try visitor.visitSingularInt32Field(value: self.userID, fieldNumber: 1)
    }
    if self.registerType != 0 {
      try visitor.visitSingularInt32Field(value: self.registerType, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_ChatListQueryUserRequest, rhs: Api_Core_ChatListQueryUserRequest) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.registerType != rhs.registerType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_OrphanReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OrphanReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_id"),
    2: .standard(proto: "consult_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.chatID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.consultID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chatID != 0 {
      try visitor.visitSingularInt64Field(value: self.chatID, fieldNumber: 1)
    }
    if self.consultID != 0 {
      try visitor.visitSingularInt64Field(value: self.consultID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_OrphanReq, rhs: Api_Core_OrphanReq) -> Bool {
    if lhs.chatID != rhs.chatID {return false}
    if lhs.consultID != rhs.consultID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_GetChatSessionStateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetChatSessionStateRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "tenant_id"),
    2: .standard(proto: "consult_id"),
    3: .standard(proto: "owner_id"),
    4: .standard(proto: "owner_role"),
    5: .standard(proto: "chat_id"),
    6: .standard(proto: "msg_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.tenantID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.consultID) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.ownerID) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.ownerRole) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.chatID) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.msgID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tenantID != 0 {
      try visitor.visitSingularInt32Field(value: self.tenantID, fieldNumber: 1)
    }
    if self.consultID != 0 {
      try visitor.visitSingularInt64Field(value: self.consultID, fieldNumber: 2)
    }
    if self.ownerID != 0 {
      try visitor.visitSingularInt32Field(value: self.ownerID, fieldNumber: 3)
    }
    if self.ownerRole != 0 {
      try visitor.visitSingularInt32Field(value: self.ownerRole, fieldNumber: 4)
    }
    if self.chatID != 0 {
      try visitor.visitSingularInt64Field(value: self.chatID, fieldNumber: 5)
    }
    if self.msgID != 0 {
      try visitor.visitSingularInt64Field(value: self.msgID, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_GetChatSessionStateRequest, rhs: Api_Core_GetChatSessionStateRequest) -> Bool {
    if lhs.tenantID != rhs.tenantID {return false}
    if lhs.consultID != rhs.consultID {return false}
    if lhs.ownerID != rhs.ownerID {return false}
    if lhs.ownerRole != rhs.ownerRole {return false}
    if lhs.chatID != rhs.chatID {return false}
    if lhs.msgID != rhs.msgID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_GetChatSessionStateResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetChatSessionStateResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "tenant_id"),
    2: .standard(proto: "consult_id"),
    3: .standard(proto: "owner_id"),
    4: .standard(proto: "owner_role"),
    6: .standard(proto: "assign_time"),
    7: .standard(proto: "session_start_time"),
    8: .standard(proto: "client_message_time"),
    31: .standard(proto: "client_first_time"),
    9: .standard(proto: "worker_id"),
    10: .standard(proto: "worker_ping_time"),
    32: .standard(proto: "worker_first_time"),
    11: .standard(proto: "worker_message_time"),
    13: .standard(proto: "worker_consult_id"),
    14: .standard(proto: "in_time"),
    15: .standard(proto: "out_time"),
    35: .standard(proto: "last_time"),
    16: .same(proto: "timeout"),
    56: .standard(proto: "wait_response"),
    57: .standard(proto: "is_process"),
    58: .standard(proto: "is_receive"),
    59: .standard(proto: "is_in"),
    60: .standard(proto: "is_out"),
    17: .same(proto: "visible"),
    20: .same(proto: "state"),
    21: .standard(proto: "worker_state"),
    22: .standard(proto: "last_message"),
  ]

  fileprivate class _StorageClass {
    var _tenantID: Int32 = 0
    var _consultID: Int64 = 0
    var _ownerID: Int32 = 0
    var _ownerRole: Int32 = 0
    var _assignTime: Int64 = 0
    var _sessionStartTime: Int64 = 0
    var _clientMessageTime: Int64 = 0
    var _clientFirstTime: Int64 = 0
    var _workerID: Int32 = 0
    var _workerPingTime: Int64 = 0
    var _workerFirstTime: Int64 = 0
    var _workerMessageTime: Int64 = 0
    var _workerConsultID: Int64 = 0
    var _inTime: Int64 = 0
    var _outTime: Int64 = 0
    var _lastTime: Int64 = 0
    var _timeout: Int32 = 0
    var _waitResponse: Int32 = 0
    var _isProcess: Int32 = 0
    var _isReceive: Int32 = 0
    var _isIn: Int32 = 0
    var _isOut: Int32 = 0
    var _visible: Int32 = 0
    var _state: CommonChatState = .common
    var _workerState: Api_Common_WorkerState = .workerOffline
    var _lastMessage: CommonMessage? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _tenantID = source._tenantID
      _consultID = source._consultID
      _ownerID = source._ownerID
      _ownerRole = source._ownerRole
      _assignTime = source._assignTime
      _sessionStartTime = source._sessionStartTime
      _clientMessageTime = source._clientMessageTime
      _clientFirstTime = source._clientFirstTime
      _workerID = source._workerID
      _workerPingTime = source._workerPingTime
      _workerFirstTime = source._workerFirstTime
      _workerMessageTime = source._workerMessageTime
      _workerConsultID = source._workerConsultID
      _inTime = source._inTime
      _outTime = source._outTime
      _lastTime = source._lastTime
      _timeout = source._timeout
      _waitResponse = source._waitResponse
      _isProcess = source._isProcess
      _isReceive = source._isReceive
      _isIn = source._isIn
      _isOut = source._isOut
      _visible = source._visible
      _state = source._state
      _workerState = source._workerState
      _lastMessage = source._lastMessage
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._tenantID) }()
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._consultID) }()
        case 3: try { try decoder.decodeSingularInt32Field(value: &_storage._ownerID) }()
        case 4: try { try decoder.decodeSingularInt32Field(value: &_storage._ownerRole) }()
        case 6: try { try decoder.decodeSingularInt64Field(value: &_storage._assignTime) }()
        case 7: try { try decoder.decodeSingularInt64Field(value: &_storage._sessionStartTime) }()
        case 8: try { try decoder.decodeSingularInt64Field(value: &_storage._clientMessageTime) }()
        case 9: try { try decoder.decodeSingularInt32Field(value: &_storage._workerID) }()
        case 10: try { try decoder.decodeSingularInt64Field(value: &_storage._workerPingTime) }()
        case 11: try { try decoder.decodeSingularInt64Field(value: &_storage._workerMessageTime) }()
        case 13: try { try decoder.decodeSingularInt64Field(value: &_storage._workerConsultID) }()
        case 14: try { try decoder.decodeSingularInt64Field(value: &_storage._inTime) }()
        case 15: try { try decoder.decodeSingularInt64Field(value: &_storage._outTime) }()
        case 16: try { try decoder.decodeSingularInt32Field(value: &_storage._timeout) }()
        case 17: try { try decoder.decodeSingularInt32Field(value: &_storage._visible) }()
        case 20: try { try decoder.decodeSingularEnumField(value: &_storage._state) }()
        case 21: try { try decoder.decodeSingularEnumField(value: &_storage._workerState) }()
        case 22: try { try decoder.decodeSingularMessageField(value: &_storage._lastMessage) }()
        case 31: try { try decoder.decodeSingularInt64Field(value: &_storage._clientFirstTime) }()
        case 32: try { try decoder.decodeSingularInt64Field(value: &_storage._workerFirstTime) }()
        case 35: try { try decoder.decodeSingularInt64Field(value: &_storage._lastTime) }()
        case 56: try { try decoder.decodeSingularInt32Field(value: &_storage._waitResponse) }()
        case 57: try { try decoder.decodeSingularInt32Field(value: &_storage._isProcess) }()
        case 58: try { try decoder.decodeSingularInt32Field(value: &_storage._isReceive) }()
        case 59: try { try decoder.decodeSingularInt32Field(value: &_storage._isIn) }()
        case 60: try { try decoder.decodeSingularInt32Field(value: &_storage._isOut) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._tenantID != 0 {
        try visitor.visitSingularInt32Field(value: _storage._tenantID, fieldNumber: 1)
      }
      if _storage._consultID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._consultID, fieldNumber: 2)
      }
      if _storage._ownerID != 0 {
        try visitor.visitSingularInt32Field(value: _storage._ownerID, fieldNumber: 3)
      }
      if _storage._ownerRole != 0 {
        try visitor.visitSingularInt32Field(value: _storage._ownerRole, fieldNumber: 4)
      }
      if _storage._assignTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._assignTime, fieldNumber: 6)
      }
      if _storage._sessionStartTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._sessionStartTime, fieldNumber: 7)
      }
      if _storage._clientMessageTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._clientMessageTime, fieldNumber: 8)
      }
      if _storage._workerID != 0 {
        try visitor.visitSingularInt32Field(value: _storage._workerID, fieldNumber: 9)
      }
      if _storage._workerPingTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._workerPingTime, fieldNumber: 10)
      }
      if _storage._workerMessageTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._workerMessageTime, fieldNumber: 11)
      }
      if _storage._workerConsultID != 0 {
        try visitor.visitSingularInt64Field(value: _storage._workerConsultID, fieldNumber: 13)
      }
      if _storage._inTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._inTime, fieldNumber: 14)
      }
      if _storage._outTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._outTime, fieldNumber: 15)
      }
      if _storage._timeout != 0 {
        try visitor.visitSingularInt32Field(value: _storage._timeout, fieldNumber: 16)
      }
      if _storage._visible != 0 {
        try visitor.visitSingularInt32Field(value: _storage._visible, fieldNumber: 17)
      }
      if _storage._state != .common {
        try visitor.visitSingularEnumField(value: _storage._state, fieldNumber: 20)
      }
      if _storage._workerState != .workerOffline {
        try visitor.visitSingularEnumField(value: _storage._workerState, fieldNumber: 21)
      }
      try { if let v = _storage._lastMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 22)
      } }()
      if _storage._clientFirstTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._clientFirstTime, fieldNumber: 31)
      }
      if _storage._workerFirstTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._workerFirstTime, fieldNumber: 32)
      }
      if _storage._lastTime != 0 {
        try visitor.visitSingularInt64Field(value: _storage._lastTime, fieldNumber: 35)
      }
      if _storage._waitResponse != 0 {
        try visitor.visitSingularInt32Field(value: _storage._waitResponse, fieldNumber: 56)
      }
      if _storage._isProcess != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isProcess, fieldNumber: 57)
      }
      if _storage._isReceive != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isReceive, fieldNumber: 58)
      }
      if _storage._isIn != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isIn, fieldNumber: 59)
      }
      if _storage._isOut != 0 {
        try visitor.visitSingularInt32Field(value: _storage._isOut, fieldNumber: 60)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_GetChatSessionStateResponse, rhs: Api_Core_GetChatSessionStateResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._tenantID != rhs_storage._tenantID {return false}
        if _storage._consultID != rhs_storage._consultID {return false}
        if _storage._ownerID != rhs_storage._ownerID {return false}
        if _storage._ownerRole != rhs_storage._ownerRole {return false}
        if _storage._assignTime != rhs_storage._assignTime {return false}
        if _storage._sessionStartTime != rhs_storage._sessionStartTime {return false}
        if _storage._clientMessageTime != rhs_storage._clientMessageTime {return false}
        if _storage._clientFirstTime != rhs_storage._clientFirstTime {return false}
        if _storage._workerID != rhs_storage._workerID {return false}
        if _storage._workerPingTime != rhs_storage._workerPingTime {return false}
        if _storage._workerFirstTime != rhs_storage._workerFirstTime {return false}
        if _storage._workerMessageTime != rhs_storage._workerMessageTime {return false}
        if _storage._workerConsultID != rhs_storage._workerConsultID {return false}
        if _storage._inTime != rhs_storage._inTime {return false}
        if _storage._outTime != rhs_storage._outTime {return false}
        if _storage._lastTime != rhs_storage._lastTime {return false}
        if _storage._timeout != rhs_storage._timeout {return false}
        if _storage._waitResponse != rhs_storage._waitResponse {return false}
        if _storage._isProcess != rhs_storage._isProcess {return false}
        if _storage._isReceive != rhs_storage._isReceive {return false}
        if _storage._isIn != rhs_storage._isIn {return false}
        if _storage._isOut != rhs_storage._isOut {return false}
        if _storage._visible != rhs_storage._visible {return false}
        if _storage._state != rhs_storage._state {return false}
        if _storage._workerState != rhs_storage._workerState {return false}
        if _storage._lastMessage != rhs_storage._lastMessage {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_GetChatStateReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetChatStateReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "consult_id"),
    2: .standard(proto: "chat_ids"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.consultID) }()
      case 2: try { try decoder.decodeRepeatedInt64Field(value: &self.chatIds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.consultID != 0 {
      try visitor.visitSingularInt64Field(value: self.consultID, fieldNumber: 1)
    }
    if !self.chatIds.isEmpty {
      try visitor.visitPackedInt64Field(value: self.chatIds, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_GetChatStateReq, rhs: Api_Core_GetChatStateReq) -> Bool {
    if lhs.consultID != rhs.consultID {return false}
    if lhs.chatIds != rhs.chatIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_StateItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StateItem"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_id"),
    2: .standard(proto: "user_id"),
    3: .standard(proto: "is_time_out"),
    4: .standard(proto: "expire_seconds"),
    5: .standard(proto: "now_time"),
    6: .standard(proto: "worker_id"),
    7: .standard(proto: "last_msg_time"),
    8: .standard(proto: "assign_time"),
    9: .standard(proto: "transfer_in_time"),
    10: .standard(proto: "transfer_out_time"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.chatID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.userID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isTimeOut) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.expireSeconds) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.nowTime) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.workerID) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.lastMsgTime) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.assignTime) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.transferInTime) }()
      case 10: try { try decoder.decodeSingularInt64Field(value: &self.transferOutTime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chatID != 0 {
      try visitor.visitSingularInt64Field(value: self.chatID, fieldNumber: 1)
    }
    if self.userID != 0 {
      try visitor.visitSingularInt32Field(value: self.userID, fieldNumber: 2)
    }
    if self.isTimeOut != false {
      try visitor.visitSingularBoolField(value: self.isTimeOut, fieldNumber: 3)
    }
    if self.expireSeconds != 0 {
      try visitor.visitSingularInt64Field(value: self.expireSeconds, fieldNumber: 4)
    }
    if self.nowTime != 0 {
      try visitor.visitSingularInt64Field(value: self.nowTime, fieldNumber: 5)
    }
    if self.workerID != 0 {
      try visitor.visitSingularInt32Field(value: self.workerID, fieldNumber: 6)
    }
    if self.lastMsgTime != 0 {
      try visitor.visitSingularInt64Field(value: self.lastMsgTime, fieldNumber: 7)
    }
    if self.assignTime != 0 {
      try visitor.visitSingularInt64Field(value: self.assignTime, fieldNumber: 8)
    }
    if self.transferInTime != 0 {
      try visitor.visitSingularInt64Field(value: self.transferInTime, fieldNumber: 9)
    }
    if self.transferOutTime != 0 {
      try visitor.visitSingularInt64Field(value: self.transferOutTime, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_StateItem, rhs: Api_Core_StateItem) -> Bool {
    if lhs.chatID != rhs.chatID {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.isTimeOut != rhs.isTimeOut {return false}
    if lhs.expireSeconds != rhs.expireSeconds {return false}
    if lhs.nowTime != rhs.nowTime {return false}
    if lhs.workerID != rhs.workerID {return false}
    if lhs.lastMsgTime != rhs.lastMsgTime {return false}
    if lhs.assignTime != rhs.assignTime {return false}
    if lhs.transferInTime != rhs.transferInTime {return false}
    if lhs.transferOutTime != rhs.transferOutTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_GetChatStateResp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetChatStateResp"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "consult_id"),
    2: .same(proto: "items"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.consultID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.consultID != 0 {
      try visitor.visitSingularInt64Field(value: self.consultID, fieldNumber: 1)
    }
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_GetChatStateResp, rhs: Api_Core_GetChatStateResp) -> Bool {
    if lhs.consultID != rhs.consultID {return false}
    if lhs.items != rhs.items {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_GetChatStateRespV1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetChatStateRespV1"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "consult_id"),
    2: .standard(proto: "chat_ids"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.consultID) }()
      case 2: try { try decoder.decodeRepeatedInt64Field(value: &self.chatIds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.consultID != 0 {
      try visitor.visitSingularInt64Field(value: self.consultID, fieldNumber: 1)
    }
    if !self.chatIds.isEmpty {
      try visitor.visitPackedInt64Field(value: self.chatIds, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_GetChatStateRespV1, rhs: Api_Core_GetChatStateRespV1) -> Bool {
    if lhs.consultID != rhs.consultID {return false}
    if lhs.chatIds != rhs.chatIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_ChatFaqRemarkReq: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatFaqRemarkReq"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.chatID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.chatID != 0 {
      try visitor.visitSingularInt64Field(value: self.chatID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_ChatFaqRemarkReq, rhs: Api_Core_ChatFaqRemarkReq) -> Bool {
    if lhs.chatID != rhs.chatID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Api_Core_ChatFaqRemarkResp: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChatFaqRemarkResp"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "chat_remark"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.chatRemark) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chatRemark.isEmpty {
      try visitor.visitSingularStringField(value: self.chatRemark, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Api_Core_ChatFaqRemarkResp, rhs: Api_Core_ChatFaqRemarkResp) -> Bool {
    if lhs.chatRemark != rhs.chatRemark {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
